Master
AMTANGEE/Tools.NotebookMaintenance pull request #3
Opened 2018-10-21 12:12 UTC by JoergWaechtler

change Mainform Startpositon = CenterScreenn
add filter for filetypes (based on replication database)

2018-10-21 12:17 UTC, JoergWaechtler reviewed
Komisch: ich hatte bei den SQL's am Anfang einfach ein Leerzeichen vergessen. Also request zurück gezogen und ein neues erstellt (wo die Leerzeichen vor dem "and" in beiden Routinen drin steht (Vorschau+Durchführen). Aber hier sehe ich wieder die Leerzeichen nicht.
Ich habe da irgend was beim Request wieder falsch gemacht. GitHub mag ich schon jetzt nicht...

2018-10-21 12:24 UTC, JoergWaechtler commented
[Chance.txt](https://github.com/AMTANGEE/Tools.NotebookMaintenance/files/2499112/Chance.txt)

2018-10-21 13:15 UTC, Rfraatz commented
Ein Push auf deine Repository hast du aber gemacht, oder? Du musst ja zusätzlich zum Commit auch immer ein Push machen, um dein Repository zu aktualisieren und dann ein Pull Request mit den aktuellen Daten zu machen.

2018-10-21 14:30 UTC, JoergWaechtler commented
Ich glaube jetzt passt es :-)

2018-10-23 15:34 UTC, Rfraatz requested changes
please fix typo

2018-10-23 15:34 UTC, Rfraatz commented on AMTANGEE.Tools.NotebookMaintenance/MainForm.cs
> +                    MessageBox.Show("Es wurden keine Dateiendung in der Datenbank gefunden. Die Option wird jetzt autoamtisch deaktivert.");
Typo

2018-10-30 20:14 UTC, merged